import PDFDocument from 'pdfkit';

const BRAND = {
  primary: '#8F5C45',
  primaryDark: '#774A37',
  heading: '#1a1a2e',
  body: '#374151',
  muted: '#6b7280',
  light: '#f3f4f6',
  border: '#e5e7eb',
  white: '#ffffff',
};

function generateReferenceId() {
  const now = new Date();
  const date = now.toISOString().slice(0, 10).replace(/-/g, '');
  const rand = Math.floor(100000 + Math.random() * 900000);
  return `CA-${date}-${rand}`;
}

function formatDatePKT(dateStr) {
  const date = dateStr ? new Date(dateStr) : new Date();
  return date.toLocaleString('en-US', {
    timeZone: 'Asia/Karachi',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatTimePKT(dateStr) {
  const date = dateStr ? new Date(dateStr) : new Date();
  return date.toLocaleString('en-US', {
    timeZone: 'Asia/Karachi',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
}

export function createDocument(options = {}) {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 70, left: 50, right: 50 },
    bufferPages: true,
    info: {
      Title: options.title || 'Code Amigo Document',
      Author: 'Code Amigo',
      Creator: 'Code Amigo PDF Engine',
    },
  });

  return doc;
}

export function drawHeader(doc, { title, subtitle }) {
  const w = doc.page.width;

  doc.rect(0, 0, w, 120).fill(BRAND.primary);

  doc.fontSize(11).fill('#ffffff').font('Helvetica-Bold')
    .text('CODE AMIGO', 50, 35, { width: w - 100 });

  doc.fontSize(22).font('Helvetica-Bold')
    .text(title, 50, 58, { width: w - 100 });

  if (subtitle) {
    doc.fontSize(11).font('Helvetica').fill('rgba(255,255,255,0.8)')
      .text(subtitle, 50, 88, { width: w - 100 });
  }

  doc.moveDown(0);
  doc.y = 120;

  doc.moveTo(50, doc.y).lineTo(w - 50, doc.y).lineWidth(1).stroke(BRAND.border);
  doc.y += 20;
}

export function drawSectionTitle(doc, text) {
  const w = doc.page.width;
  doc.fontSize(13).font('Helvetica-Bold').fill(BRAND.primary)
    .text(text, 50, doc.y, { width: w - 100 });
  doc.y += 6;

  doc.moveTo(50, doc.y).lineTo(w - 50, doc.y).lineWidth(0.5).stroke(BRAND.border);
  doc.y += 16;
}

export function drawInfoRow(doc, label, value, options = {}) {
  const w = doc.page.width;
  const labelX = 50;
  const valueX = options.valueX || 200;
  const valueWidth = w - valueX - 50;

  doc.fontSize(10).font('Helvetica').fill(BRAND.muted)
    .text(label, labelX, doc.y, { width: valueX - labelX - 10 });

  doc.fontSize(10).font('Helvetica-Bold').fill(BRAND.heading)
    .text(value || '—', valueX, doc.y - 14, { width: valueWidth });

  doc.y += 8;

  if (!options.noBorder) {
    doc.moveTo(50, doc.y).lineTo(w - 50, doc.y).lineWidth(0.3).stroke(BRAND.border);
    doc.y += 12;
  }
}

export function drawInfoGrid(doc, rows) {
  const w = doc.page.width;
  const colWidth = (w - 100 - 20) / 2;
  const col1LabelX = 50;
  const col1ValueX = 170;
  const col2LabelX = 50 + colWidth + 20;
  const col2ValueX = col2LabelX + 120;

  let y = doc.y;

  for (let i = 0; i < rows.length; i += 2) {
    const left = rows[i];
    const right = rows[i + 1];

    if (left) {
      doc.fontSize(10).font('Helvetica').fill(BRAND.muted)
        .text(left.label, col1LabelX, y, { width: col1ValueX - col1LabelX - 10 });
      doc.fontSize(10).font('Helvetica-Bold').fill(BRAND.heading)
        .text(left.value || '—', col1ValueX, y, { width: colWidth - (col1ValueX - col1LabelX) });
    }

    if (right) {
      doc.fontSize(10).font('Helvetica').fill(BRAND.muted)
        .text(right.label, col2LabelX, y, { width: col2ValueX - col2LabelX - 10 });
      doc.fontSize(10).font('Helvetica-Bold').fill(BRAND.heading)
        .text(right.value || '—', col2ValueX, y, { width: colWidth - (col2ValueX - col2LabelX) });
    }

    const usedHeight = doc.y - y;
    y += Math.max(usedHeight, 36) + 12;

    doc.moveTo(50, y - 8).lineTo(w - 50, y - 8).lineWidth(0.3).stroke(BRAND.border);
  }

  doc.y = y;
}

export function drawBlockText(doc, text) {
  const w = doc.page.width;

  doc.fontSize(10).font('Helvetica').fill(BRAND.body)
    .text(text || '—', 50, doc.y, {
      width: w - 100,
      lineGap: 4,
      align: 'left',
    });
  doc.y += 16;
}

export function drawFooter(doc) {
  const w = doc.page.width;
  const h = doc.page.height;
  const bottomY = h - 50;

  doc.moveTo(50, bottomY - 10).lineTo(w - 50, bottomY - 10).lineWidth(0.3).stroke(BRAND.border);

  const pages = doc.bufferedPageRange();
  for (let i = pages.start; i < pages.start + pages.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(8).font('Helvetica').fill(BRAND.muted)
      .text('Generated by Code Amigo  |  www.codeamigo.com', 50, bottomY, {
        width: w - 100,
        align: 'center',
      });

    if (pages.count > 1) {
      doc.text(`Page ${i - pages.start + 1} of ${pages.count}`, 50, bottomY + 12, {
        width: w - 100,
        align: 'center',
      });
    }
  }
}

export { generateReferenceId, formatDatePKT, formatTimePKT, BRAND };
